# ========================================== #
#      AxoCrafT TrapPlugin Konfigürasyon      #
# ========================================== #

# Trap satın alma ve satış fiyatı (60.000$)
trap-price: 60000.0

# Oluşturulan trap sayacı (Otomatik artar)
trap-count: 0

# Traplerin kaydedildiği veri alanı (Otomatik dolacaktır)
traps: {}

