
name: TrapPlugin
version: 1.0.0
main: com.craftaxo.trapplugin.Main
api-version: 1.20
softdepend: [Vault]
description: Trap yonetim ve klan benzeri arazi koruma eklentisi.
commands:
  trap:
    description: Trap yonetim komutlari
    usage: /trap
